version: "2.2"

services:
  fis-express:
    image: johnnythai04/fis-express
    ports: 
      - "4001:4001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
  fis-webapp:
    image: johnnythai04/fis-webapp
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_ENV=production
